### ISSUE TITLE
Discord doesn't notify me when a message with mention has arrived. 

### ISSUE THREAD

**Issue by everalan10** [jenkinsci/discord-notifier-plugin#10]
Hi, thanks for this plugin is awesome.

We are a team with 10 people into a Discord Server, but we dont want to advice to all when a fail or succeed has been occurred. We mute the channel and only the interested people must read it. 

The problem is every time that we receive a message from Jenkins, the mentions are not accumulated into the Discord mentions area. appears empty.

![mentions](https://user-images.githubusercontent.com/6885581/63377300-14c71400-c34d-11e9-8abd-d80c2f190583.png)

But the message appears ok with the name of the user.
![Discord mention](https://user-images.githubusercontent.com/6885581/63377023-5acfa800-c34c-11e9-9792-ae5ceed19f79.png)

Again, Thanks.

**Comment by KocproZ** [comment]
Unfortunately mentioning people inside the embed doesn't send a notification (discord doesn't allow that).  
 In the settings for this plugin there is a text field called Notes. Putting mentions there works, but it will be displayed outside the embed.

**Comment by everalan10** [comment]
Oh it's ok no problem. do you know how to pass that "notes" parameter into a pipeline style command?

**Comment by melt7777** [comment]
Here is a example of what I am using in my Jenkinsfile (Using Scripted Pipeline, may differ for Declarative Pipeline)

```groovy
// URL of Discord webhook for posting build notifications
      def discordURL = 'https://discordapp.com/api/webhooks/Shortkey/Longkey'
      // URL of image png/jpg to place to right of Discord build notifications
      def discordImage = 'https://blabla.png'
      
      def discordDesc = "description\n"
      def discordFooter = "footer desc with vars: ${env.JOB_BASE_NAME}` (build #${BUILD_NUMBER})"
      def discordTitle = "${buildName} (devel)"
      discordSend description: discordDesc, 
                  footer: discordFooter, 
                  link: env.JOB_URL, 
                  result: currentBuild.currentResult, 
                  title: discordTitle, 
                  webhookURL: discordURL, 
                  successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS'), 
                  thumbnail: discordImage
   }
```

Hope this helps - and great work you all! Thanks so much :) 

~ melt
getpimp.org | miner.farm

**Comment by KocproZ** [comment]
@everalan10 I just pushed an update to the plugin, from now on you can pass `notes` parameter into the pipeline (`notes: "text"`). Let me know if this works for you.

**Comment by melt7777** [comment]
Hi KocproZ, Thanks for adding a feature.

I have added the `notes: "note output here"` parameter to the above code, and when the plugin update is available in Jenkins Plugin Manager I will try it with @ mentions as well and post my results here.

~ melt
getpimp.org | miner.farm

**Comment by melt7777** [comment]
Test results for Declarative Pipeline code using "notes" parameter with mentions. The test failed, and the mentions were not picked up by discord.

Discord-notifier version: 1.4.10

```
      discordSend description: discordDesc, 
                  footer: discordFooter, 
                  link: env.JOB_URL, 
                  result: currentBuild.currentResult, 
                  title: discordTitle, 
                  webhookURL: discordURL, 
                  successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS'),
                  thumbnail: discordImage,
                  notes: "Here's some Notes! @melt @melt#2019 @melt (getpimp.org)#2019 @Support"
   }
```

Resulting output in Discord: 

![image](https://user-images.githubusercontent.com/4382542/64974295-845fee80-d87a-11e9-99c5-736c37abf9c0.png)


Hope this helps, let me know if you would like any other testing performed. Your work on this project is always appreciated!

~ melt
getpimp.org | miner.farm

**Comment by KocproZ** [comment]
To get mentions to work from webhook you have to mention someone by their id.
For example when I put this in notes: `Hey <@151765009876123648>, the build is done!`, I get this:
![image](https://user-images.githubusercontent.com/8616451/64988251-5c4cab80-d8cb-11e9-9c27-591d003101e6.png)

**Comment by melt7777** [comment]
Aha, thank you, the <@id> syntax worked great: 
![image](https://user-images.githubusercontent.com/4382542/64992694-702fe780-d8a2-11e9-804c-ce9dffb43d4c.png)

Thanks again!
