### ISSUE TITLE
Feature Request: Send notification when build starts!

### ISSUE THREAD

**Issue by Fyb3roptik** [jenkinsci/discord-notifier-plugin#12]
We are moving from Slack to Discord and Slack will let us know the build started. I currently only have a way to see when its finished! If there is a way, please let me know

**Comment by KocproZ** [comment]
If you are using a pipeline just add `discordSend` at the begging of the pipeline.
If you want to send the notification from freestyle project unfortunately you can't since it's a Post-build step and I can't find how slack plugin does that.

**Comment by Fyb3roptik** [comment]
They have theirs in the post build, You just check the box that says to notify when it starts. So I will assume jenkins has a way to detect that

**Comment by Fyb3roptik** [comment]
And I am using Freestyle

**Comment by KocproZ** [comment]
Oh, now I see how they are doing it.
I will try to add that option over the weekend.

**Comment by KocproZ** [comment]
The change is now in jenkins repos.
I wasn't sure how the notification should look like so if you have any suggestions you can let me know.

**Comment by melt7777** [comment]
Hello KocproZ, thank you for adding this feature, and making it easy to update and test. I have successfully tested the new feature. I like how it has a beginning and then end. Great work!!

![image](https://user-images.githubusercontent.com/4382542/64973776-9f7e2e80-d879-11e9-98ff-a12d11e2bd79.png)

~ melt
getpimp.org | miner.farm

**Comment by Fyb3roptik** [comment]
Confirmed working. THANK YOU!!!!!!!
