### ISSUE TITLE
ENV variables not working in message

### ISSUE THREAD

**Issue by Fyb3roptik** [jenkinsci/discord-notifier-plugin#14]
I have some env variables that get set during build and I am trying to pass them in the Note, but it comes across as $ENV_VAR instead of the actual text

**Comment by Fyb3roptik** [comment]
@KocproZ Any help here would be appreciated!

**Comment by KocproZ** [comment]
Sorry, I didn't have time to work on this project recently, I will try to take a look at this issue today.

**Comment by Fyb3roptik** [comment]
This is working. THANK YOU!!!!

**Comment by melt7777** [comment]
Excellent work - just wanted to add some thanks.

~ melt 
getpimp.org | miner.farm
