### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by AgentSlim** [jenkinsci/discord-notifier-plugin#15]
Hello,

can I also use other placeholders like build number, build log, chanchges, etc.?

**Comment by KocproZ** [comment]
I am not sure what you mean, can you explain what you want to achieve in more detail?
Is it related to normal builds or pipeline?

**Comment by rlewicki** [comment]
@KocproZ I think @AgentSlim meant he would like to use variables like `BUILD_NUMBER` and `JOB_NAME`. I am interestend if this is possible using normal builds as I would like to post custom message based on those parameters.

**Comment by melt7777** [comment]
Hello, not sure if this well help your use case....

I am able to use variables in declarative pipeline, see examples below:

```
      def discordTitle = "${buildName}"
      
      discordSend description: discordDesc, 
                  footer: discordFooter, 
                  link: env.JOB_URL, 
                  result: currentBuild.currentResult, 
                  title: discordTitle, 
                  webhookURL: discordURL, 
                  successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS'), 
                  thumbnail: discordImage
   }
}```

Agree on usefulness of extending Jenkins job environment vars into the plugin.

Thanks all!

~ melt
Devops, miner.farm

**Comment by rlewicki** [comment]
@melt7777 that's something, but are you by any chance aware if I can do it somehow in normal build? I already tried `{JOB_NAME}`, `{ENV:JOB_NAME}`, `env.JOB_NAME`. None worked for me unfortunately.
