### ISSUE TITLE
Cannot find where to configure Discord Notifier.

### ISSUE THREAD

**Issue by Void9711** [jenkinsci/discord-notifier-plugin#17]
I started a Jenkins sever on my local machine, created jobs and installed this plugin. But I cannot find where to use it, I couldn't find out the same options like the pictures in your [guide](https://github.com/jenkinsci/discord-notifier-plugin#usage) instructs.

I just got this at my job configure:

![image](https://user-images.githubusercontent.com/48246306/77164667-c00a9800-6aeb-11ea-8621-c217503ac7e7.png)

Nothing like 'Add post-build action', are there something I did wrong?

**Comment by KocproZ** [comment]
At the bottom of the configuration page there should be a section called "Post-build Actions", try looking there.

**Comment by Void9711** [comment]
Thanks @KocproZ , I've found the wrong point then. The jenkins item I've created before was not a freestyle project so there will not be any post-build actions configuration.

As this issue describes: https://issues.jenkins-ci.org/browse/JENKINS-52709

**Comment by melt7777** [comment]
Hello, works with Freestyle projects, and also, I have been using this plugin successfully in Groovy Declarative Pipeline for a few years, here is a sample of code that you could try. Hope that it helps.

```groovy
def discordTitle = "${buildName}"
      
      discordSend description: discordDesc, 
                  footer: discordFooter, 
                  link: env.JOB_URL, 
                  result: currentBuild.currentResult, 
                  title: discordTitle, 
                  webhookURL: discordURL, 
                  successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS'), 
                  thumbnail: discordImage
```

**Comment by Void9711** [comment]
> Hello, works with Freestyle projects, and also, I have been using this plugin successfully in Groovy Declarative Pipeline for a few years, here is a sample of code that you could try. Hope that it helps.
> 
> ```groovy
> def discordTitle = "${buildName}"
> // other variables declared
> discordSend description: discordDesc, 
>                   footer: discordFooter, 
>                   link: env.JOB_URL, 
>                   result: currentBuild.currentResult, 
>                   title: discordTitle, 
>                   webhookURL: discordURL, 
>                   successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS'), 
>                   thumbnail: discordImage
> ```

Yes it's also an answer!

**Comment by Skyridr** [comment]
> Hello, works with Freestyle projects, and also, I have been using this plugin successfully in Groovy Declarative Pipeline for a few years, here is a sample of code that you could try. Hope that it helps.
> 
> ```groovy
> def discordTitle = "${buildName}"
> // other variables declared
> discordSend description: discordDesc, 
>                   footer: discordFooter, 
>                   link: env.JOB_URL, 
>                   result: currentBuild.currentResult, 
>                   title: discordTitle, 
>                   webhookURL: discordURL, 
>                   successful: currentBuild.resultIsBetterOrEqualTo('SUCCESS'), 
>                   thumbnail: discordImage
> ```

Did something change? It no longer appears to work.

**Comment by KocproZ** [comment]
I think it will work if you put the url in single quotes ` webhookURL: 'https://.......'`.
In groovy `'abc'` and `"abc"` are different strings and I think somebody had this problem before
