### ISSUE TITLE
Please enter a valid Discord webhook URL

### ISSUE THREAD

**Issue by Artuto** [jenkinsci/discord-notifier-plugin#19]
Discord is changing domains from Discordapp.com to Discord.com, and making the former unusable on November 7th, 2020.

If i currently set a discord.com Webhook URL i get the `Please enter a valid Discord webhook URL.` error/warning.

**Comment by KocproZ** [comment]
Thanks for the info.
Can you link me the source of this information? I couldn't find it anywhere, and my discord server gives me url pointing to `discordapp.com`

**Comment by Artuto** [comment]
https://github.com/discord/discord-api-docs/issues/1585

**Comment by KocproZ** [comment]
Thanks!
