### ISSUE TITLE
Feature Request: Customize name and avatar

### ISSUE THREAD

**Issue by timbru31** [jenkinsci/discord-notifier-plugin#20]
They are currently hardcoded:
https://github.com/jenkinsci/discord-notifier-plugin/blob/master/src/main/java/nz/co/jammehcow/jenkinsdiscord/DiscordWebhook.java#L61-L62

It would be nice, if those can be configured, too.

Thanks a lot for the plugin! :)

**Comment by melt7777** [comment]
+1 on this feature request. Currently, the implementation via Declarative Pipeline DOES support full control, but the Freestyle Post-build step implementation does not. Would be nice to set these per-job :)

Thanks all!!

~ melt
miner.farm DevOps

**Comment by sky-lake** [comment]
I would also like to see support for specifying customUsername / customAvatarUrl for pipeline step.  (Specifically, I'd like to be able to pass NULL or "" or something to force discord to use the already configured integration webhook profile picture & name)

**Comment by Tri0L** [comment]
Hello!

+1 Need it functionality.
