### ISSUE TITLE
Environment variables parsing in message Title and Description

### ISSUE THREAD

**Issue by Leonidius20** [jenkinsci/discord-notifier-plugin#26]
For example, this setup
![image](https://user-images.githubusercontent.com/25536411/90954412-bc08ea80-e47c-11ea-84bb-332b4373930a.png)
results in this:
![image](https://user-images.githubusercontent.com/25536411/90954417-ce832400-e47c-11ea-9c7b-be67d7f77936.png)

Could environment variables parsing be added for these fields?

**Comment by KocproZ** [comment]
It already works, you just have to use right values
`$BUILD_NUMBER` and `${BUILD_NUMBER}` both work

**Comment by Leonidius20** [comment]
oh, ok then
