### ISSUE TITLE
Question: Jenkins keep warning me "Please enter a valid Discord webhook URL."

### ISSUE THREAD

**Issue by lonyphus** [jenkinsci/discord-notifier-plugin#32]
I did paste Discord webhook correctly but Jenkins keep warning me.

And it seems like not working at all.

What could I do?

webhook looks like https://discord.com/api/webhooks/{webhook.id}/{webhook.token}

**Comment by KocproZ** [comment]
Sorry for that, I had it fixed but didn't release it. I just pushed an update.
