### ISSUE TITLE
Send only when fail button check

### ISSUE THREAD

**Issue by kocoten1992** [jenkinsci/discord-notifier-plugin#39]
### Feature Request

We have a `Only send on state change` check, but the use case here is quite different.

For example, I have a backup database job run everyday, I don't want to notify system admin when thing going well but do want to remind them everyday when the job fail.

They might miss when backup job fail the first time and subsequent fail will go unnoticed since it the same behavior with successful, hence I propose `Send only when fail` button.

**Comment by KocproZ** [comment]
Implemented in #49

**Comment by kocoten1992** [comment]
@bootjp, @KocproZ, Thank you!

**Comment by bootjp** [comment]
Thank you for merging.
