### ISSUE TITLE
`nulljob` artifact links

### ISSUE THREAD

**Issue by hedin-hiervard** [jenkinsci/discord-notifier-plugin#5]
```
DS #203
Build: 203
Status: success
Changes:
- be5f20 library working - Andrey Kiryushkin
- 1cf8c1 the spell bar - Andrey Kiryushkin

Artifacts:
- nulljob/DS/203/artifact/builds/DS-203-1cf8c1-macOS-debug.zip
- nulljob/DS/203/artifact/builds/DS-203-1cf8c1-Windows-debug.zip
```

Jenkins URL is set in the global settings so it's not an issue.

**Comment by hedin-hiervard** [comment]
The plugin version is `1.5.0`

**Comment by KocproZ** [comment]
I checked for possible causes, but I couldn't find any possible cause other than Jenkins URL not being set.
Have you tried changing the Jenkins URL and then checking if it works?
If it doesn't I don't have any other ideas.

**Comment by hedin-hiervard** [comment]
Yes, I tried and it didn't help.
What DID help is removing the post-build action and re-adding it back with the same settings.
Seems it has something to do with Jenkins / Plugin update
