### ISSUE TITLE
Feature Request: Custom message and way to remove changeset

### ISSUE THREAD

**Issue by furai** [jenkinsci/discord-notifier-plugin#6]
Hello,

I'd like to be able to add custom message to the notifications sent. I need it to notify some discord members or actually give more info about the build.

And since this job doesn't have any repository tied to it - there will never be any changset to show. Thus I'd like to remove it altogether from the message.

Thanks in advance for your time taken into replying.

Cheers,
Furai

**Comment by KocproZ** [comment]
Hello,
I made it that changeset won't show if there is no repo tied to the job.
I added a custom field called notes too. It looks like this:
![screenshot_2019-02-27_18 28 49_357x227](https://user-images.githubusercontent.com/8616451/53510275-dba89800-3abd-11e9-85f4-4f6c2d590866.png)
Let me know if this is what you had in mind.
Also, if you want to test this already grab hpi file from [here](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fdiscord-notifier-plugin/detail/master/22/artifacts)

**Comment by melt7777** [comment]
Thank you very much for this great feature request and implementation!

**Comment by furai** [comment]
Great! Just what I was looking for. Maybe add ability to not show changeset even if repo is in? Sometimes you don't want to announce changes.

Thanks for working on this! :)

**Comment by furai** [comment]
Sorry to bump this but have you thought of proposed change above? 
Also when can we expect updated version to be pushed to Jenkins' repos?

**Comment by KocproZ** [comment]
Sorry, I forgot about this.
I think checkbox to hide changeset is a good idea, easy to add too.
I'm going to add it and push changes to jenkins today or tomorrow.

**Comment by furai** [comment]
Thank you a lot for working on this. :)

**Comment by furai** [comment]
Ok, I've checked and almost everything is perfect. Except for the fact how embeds work on discord. I intended to use that extra notes to tag people that needed to see that build was out `@here` or different. 

But, you can't tag people in discord's embeds. It won't send any kind of notification.

So my question would be - could we add some extra message that would be outside of the embed? Or let us choose whether we want the notes to appear in embed or not?

Thanks in advance! I really appreciate your hard work on this! :)

**Comment by melt7777** [comment]
Hello @furai, I was wondering if you placed their full Discord Tag into the comment, this is sometimes required for Discord to provide a Mention link. Example: Instead of @melt you would tag @melt#2019 

See if this allows the Mention Link to be created for you.

PS Thank you very much KocproZ :) 

Thanks!
~ melt
getpimp.org | miner.farm

**Comment by furai** [comment]
I can tag, it just does not mention/give notification. That's how embeds in discord work. That's why I'm asking for additional note outside of embed.

**Comment by KocproZ** [comment]
Hello again,
Adding a note outside an embed wouldn't work, there would be the same problem.
Basically to tag people from webhook or bot you have to tag them by their discord id.
You can get that by either tagging someone with \ (For example  \\@username#1234), or by enabling developer mode, then right clicking someone > copy id.
When you have their discord id, you put it between <@>, like this: <@123450000001234567>.
Hope it helps!

**Comment by furai** [comment]
What about whole roles? I have "tester" role. And this notification is sent to the "testers" channels and I'd like it to mention preferably `@here` or that role. Maybe the fields mentioned in the message-object can be used for that?

**Comment by KocproZ** [comment]
Ok, now I get it, sorry for misunderstanding.
I will move the notes to the [webhook](https://discordapp.com/developers/docs/resources/webhook#execute-webhook) content.
Also, to mention roles you have to put role id between <@&>, like this: <@&12345678900000>.

**Comment by furai** [comment]
Yes, I tested with those IDs (`<@&>`) inside embed message sent by me using curl on my server with other people. They confirmed that they weren't tagged. Discord was smart enough to convert ID to the name of the group.

Sorry for the confusion with other message-object link. 

I can't test right now but I trust you did good job with it so just release it.

Thanks again for dealing with me and coding all of this! :)

**Comment by furai** [comment]
Tested. Everything works perfectly! Thanks a ton! 

One thing you might want to look into is this line: 
https://github.com/jenkinsci/discord-notifier-plugin/blob/master/src/main/resources/nz/co/jammehcow/jenkinsdiscord/WebhookPublisher/help-notes.html#L2

**Comment by LLlKuIIeP** [comment]
Are you sure what works? As soon as I tried it, it does not work.

**Comment by LLlKuIIeP** [comment]
Sorry, it really works. However, not as in this thread on the screenshots. Can I somehow indicate not id, but by nicknames?
