### ISSUE TITLE
Please release fix for issue: Webhooks created after July 22 don't work because the regex only expects an 18-character id

### ISSUE THREAD

**Issue by mrlowe** [jenkinsci/discord-notifier-plugin#86]
### Jenkins and plugins versions report

all

### What Operating System are you using (both controller, and any agents involved in the problem)?

windows server. not applicable.

### Reproduction steps

Create a new webhook in discord. Attempt to use said webhook in the discord plugin.

### Expected Results

Messages are sent to discord on failed builds.

### Actual Results

The user sees the error "Please enter a valid Discord webhook URL." and discord messages are never sent.

### Anything else?

This bug already has a fix merged into master, it just needs to be released: https://github.com/jenkinsci/discord-notifier-plugin/commit/6af4713ac0ff23184786532599978fb2e7e0fdbf

**Comment by KocproZ** [comment]
https://github.com/jenkinsci/discord-notifier-plugin/releases/tag/218.ve2b_887e3a_f28
