### ISSUE TITLE
Feature Request: Change domain from url when jenkins is behind nginx proxy

### ISSUE THREAD

**Issue by JayJay1989** [jenkinsci/discord-notifier-plugin#9]
When jenkins is behind a nginx proxy, the url thats included in the message starts with: "http://127.0.0.1:8989/job/G.....". There should be an option to change the prefix of the url to the actual domain, e.g. "https://sub.domain.ext/job/G...."

**Comment by KocproZ** [comment]
URL i taken from Jenkins global config. Try changing Jenkins URL in Manage Jenkins -> Configure System -> Jenkins Location.
